# Generated by Django 2.2 on 2019-04-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='refrence',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
