# Generated by Django 2.2 on 2019-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_word_refrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='refrence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='sentence',
            field=models.TextField(blank=True),
        ),
    ]
