# Generated by Django 2.2 on 2019-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_auto_20190427_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sentence',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
