# Generated by Django 2.2 on 2019-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_auto_20190427_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sentence',
            field=models.CharField(max_length=255),
        ),
    ]
